[build]
base = "frontend"
publish = "frontend/dist"
command = "cd frontend && npm install && npm run build"
functions = "frontend/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify//functions/api/:splat"
status = 200